### ISSUE TITLE
issues with fitting the posterior

### ISSUE THREAD

**Issue by ETaSky** [jsilve24/fido#5]
Hi Justin,

I have another issue when running fido on my own data. I am not sure how to describe the issue because I don't know what went wrong. It looks like there is some issues with fitting the posterior (although only a warning is generated).

After running `posterior <- refit(priors, optim_method="adam")`, I got following warning msg:
```
Warning messages:
1: In optimPibbleCollapsed(Y, upsilon, Theta %*% X, KInv, AInv, init,  :
  Max iterations hit, may not be at optima
2: In optimPibbleCollapsed(Y, upsilon, Theta %*% X, KInv, AInv, init,  :
  Max Iterations Hit, May not be at optima
3: In optimPibbleCollapsed(Y, upsilon, Theta %*% X, KInv, AInv, init,  :
  Cholesky of Hessian failed with status status Eigen::NumericalIssue
4: In optimPibbleCollapsed(Y, upsilon, Theta %*% X, KInv, AInv, init,  :
  Decomposition of Hessian Failed, returning MAP Estimate only
5: In (function (Y = NULL, X = NULL, upsilon = NULL, Theta = NULL,  :
  Laplace Approximation Failed, using MAP estimate of eta to obtain Posterior mean of Lambda and Sigma (i.e., not sampling from posterior distribution of Lambda or Sigma)
```

And then `ppc(posterior) + ggplot2::coord_cartesian(ylim=c(0, 30000))` would generate error:
```
Error in apply(pp, 1, function(x) stats::quantile(x, probs = c(0.025,  : 
  dim(X) must have a positive length
```

Not sure what went wrong. I am attaching the R codes I used to generate the data, essentially the same as tutorial, and the rds file so that you can have a look.

Thank you very much!
[fido_test.zip](https://github.com/jsilve24/fido/files/5789362/fido_test.zip)

Jincheng

**Comment by jsilve24** [comment]
Hi Jincheng, 

I was able to get it working. 
I noticed three things here. 

(1) You needed to modify you `Y` assignment line to 
`Y <- as(otu_table(dat_phylo), "matrix")
`
as otherwise, Y was actually still an "otu_table" object from phyloseq. Those phyloseq objects are hard to get rid of. (note as.matrix doesn't work for these objects you need to make the call explicit using the `as` function).. 
(2) I changed the optimizer method to `lbfgs`
`posterior <- refit(priors, optim_method="lbfgs")
`
This is far better than `adam` but I just haven't made it the default yet. 

(3) I notice you are using default priors from my vignette. I would encourage you to read the picking priors vignette and think carefully about what your prior beliefs really are. 

Best, 
Justin


[fido_run_test.R.zip](https://github.com/jsilve24/fido/files/5789608/fido_run_test.R.zip)
